include "volume_type.fbs";

namespace Types;

table Root {
        path: string;
        read_only: bool;
}

table ConsoleSize {
        height: uint32;
        width: uint32;
}

table User {
        uid: uint32;
        gid: uint32;
        umask: uint32;
        additional_gids: [uint32];
}

table IdMapping {
        container_id: uint32;
        host_id: uint32;
        size: uint32;
}

table SchedularOpts {
        flags: [string];
        policy: string;
        runtime: uint64;
        deadline: uint64;
        period: uint64;
        nice: int32;
        priority: int32;
}

table Capabilities {
        bounding: [string];
        effective: [string];
        inheritable: [string];
        permitted: [string];
        ambient: [string];
}

table RLimit {
        name: string;
        hard_limit: uint64;
        soft_limit: uint64;
}

table SeccompArg {
        op: string;
        value: uint64;
        value_two: uint64;
        index: uint32;
}

table SeccompSyscallRule {
        args: [SeccompArg];
        names: [string];
        action: string;
        errno_ret: uint32;
}

table Seccomp {
        syscalls: [SeccompSyscallRule];
        archs: [string];
        flags: [string];
        default_action: string;
        default_errno: uint32;
}

table TimeOffset {
        type: string;
        secs: int64;
        nanosecs: int64;
}

table Device {
        host_path: string;
        container_path: string;
}

table Network {
        tcp_ports: [string];
        udp_ports: [string];
        auto_tcp: bool;
        auto_udp: bool;
}

table Namespace {
        path: string;
        type: string;
}

table Mount {
        options: [string];
        flags: [string];
        attrs: [string];
        destination: string;
        type: string;
        source: string;
}

table Container {
        id: string;
        name: string;
        image: string;
        status: string;
        created_at: string;
        pid: uint32;
        net_pid: uint32;
        vfs: bool;
        no_remove: bool;
        filesystem_path: string;
        vfs_path: string;
        volumes: [PairString];

        hostname: string;
        domain_name: string;

        rootfs: Root;
        terminal: bool;
        console_size: ConsoleSize;

        user: User;
        uid_mapping: IdMapping;
        gid_mapping: IdMapping;

        env: [string];
        cwd: string;
        args: [string];

        oom_score: int32;
        schedular_opts: SchedularOpts;
        no_new_privileges: bool;
        capabilities: Capabilities;
        rlimits: [RLimit];
        rootfs_propagation: string;

        seccomp: Seccomp;
        cgroups_path: string;

        devices: [Device];
        networks: Network;
        timeoffsets: [TimeOffset];
        namespaces: [Namespace];
        mounts: [Mount];

        masked_paths: [string];
        read_only_paths: [string];
}

root_type Container;
